### PR TITLE
Add an installation from a specific fork/commit.

### PR DESCRIPTION
**Pull request by arokem**
Just a demo, so we can report this upstream to the dipy maintainers (since they seem incredulous https://github.com/dipy/dipy/pull/2759#issuecomment-1517932962).

### CODE REVIEW

**Comment by skoudoro** [comment]
this error https://github.com/tee-ar-ex/trx-python/actions/runs/4766035647/jobs/8472529136?pr=57#step:4:639

- show that cython is needed and not installed
- also, we do not have a pyproject.toml, So I do not know how it falls back to the classic installation

**Comment by skoudoro** [comment]
ok, I see, since we do not have a `pyproject.toml` 

it runs:
```
      running bdist_wheel
      running build
      running build_py
```

but before that, it seems it does not install any DIPY dependency like cython, nibabel, numpy, etc...
for now, you might have to do it manually until https://github.com/dipy/dipy/pull/2715. is done and merged

**Comment by arokem** [comment]
Thanks Serge! I'll try adding them one by one, starting with Cython, and
see whether we need also the others.

**Comment by skoudoro** [comment]
some progress with your fork, it find cython but not packaging,

**Comment by arokem** [comment]
That's why I added the two sanity checks: 

https://github.com/tee-ar-ex/trx-python/actions/runs/4769285925/jobs/8479505319?pr=57#step:5:1

and: 

https://github.com/tee-ar-ex/trx-python/actions/runs/4769285925/jobs/8479505319?pr=57#step:6:1

Python finds these two installed, but when it runs pip to install dipy, they are no where to be found. So strange.

**Comment by arokem** [comment]
I am not sure the links in my previous message work as intended. But look at the two steps before DIPY is installed ("Did we get cython in there?" and "Did we get packaging in there?"). They are both installed and importable on the CI runner, but then seem to disappear when they are needed :-/

**Comment by skoudoro** [comment]
I agree, so strange... I saw those sanity check.  I do not succed to go to your fork, is it the one with `pyproject.toml`  and your PR?

**Comment by skoudoro** [comment]
can you add packaging in this `pyproject.toml` from your fork

**Comment by arokem** [comment]
Oh yeah - good idea. Let's see how that works...

**Comment by arokem** [comment]
OK - one more try with both packaging and cython in the pyproject.

**Comment by arokem** [comment]
OK. I get the picture. Maybe we need to add all of dipy's dependencies into the pyproject file.

**Comment by skoudoro** [comment]
So it confirms that project with `pyproject.toml`  needs to have dependency that use pyproject.toml also.

that's strange but good to know

**Comment by skoudoro** [comment]
yeah! all green !

**Comment by arokem** [comment]
Yeah! 🎉 

@frheault : does this all make sense to you? To make this work, you would need to add this to your fork/branch on dipy: https://github.com/dipy/dipy/pull/2787/files, and add fury to the dependencies on the trx side.

**Comment by frheault** [comment]
This makes sense!

So I will go ahead and merge this PR, update my Dipy branch to have that new commit from Dipy and from there do some testing

**Pull request merged**
